# Generated by Django 2.0.8 on 2018-10-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180913_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('nation', models.CharField(max_length=20)),
                ('skin', models.CharField(choices=[('0', 'Branc0'), ('1', 'Amarelo'), ('2', 'Pardo'), ('3', 'Negro')], max_length=1)),
                ('gender', models.CharField(choices=[('0', 'Masculino'), ('1', 'Feminino'), ('2', 'Outro')], max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-date', '-priority', 'event')},
        ),
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.CharField(choices=[('0', 'Sem prioridade'), ('1', 'Normal'), ('2', 'Urgente'), ('3', 'Muito Urgente')], max_length=1),
        ),
    ]
